FROM php:7.2-apache
EXPOSE 80

RUN apt-get update && \
  apt-get install -y vim
  
RUN a2enmod proxy proxy_http
RUN a2ensite 000-* 001-*
COPY apache_conf/000-default.conf /etc/apache2/sites-available/
